
// Import the defineConfig function from Vite to create a configuration file.
import { defineConfig } from 'vite';
// Import the React plugin for Vite.
import react from '@vitejs/plugin-react';
// Import the path module from Node.js for working with file and directory paths.
import path from 'path';

// Define the port for the Vite development server.
export const vitePort = 3000;

// Export the Vite configuration.
export default defineConfig(({ mode }) => {
  return {
    // An array of plugins to use.
    plugins: [
      // The React plugin enables support for React.
      react(),
      // Custom plugin to handle source map requests correctly in the dev server.
      {
        name: 'handle-source-map-requests',
        apply: 'serve', // Apply this plugin only for the development server.
        configureServer(server) {
          server.middlewares.use((req, res, next) => {
            // Check if the request is for a source map file.
            if (req.url && req.url.endsWith('.map')) {
              // Rewrite the URL to remove any query string, which can cause issues.
              const cleanUrl = req.url.split('?')[0];
              req.url = cleanUrl;
            }
            // Pass control to the next middleware.
            next();
          });
        },
      },
      // Custom plugin to add CORS headers to all responses from the dev server.
      {
        name: 'add-cors-headers',
        apply: 'serve', // Apply this plugin only for the development server.
        configureServer(server) {
          server.middlewares.use((req, res, next) => {
            // Add CORS headers to allow cross-origin requests.
            res.setHeader('Access-Control-Allow-Origin', '*');
            res.setHeader(
              'Access-Control-Allow-Methods',
              'GET, POST, PUT, DELETE, PATCH, OPTIONS',
            );
            res.setHeader(
              'Access-Control-Allow-Headers',
              'Content-Type, Authorization, X-Requested-With',
            );

            // Handle pre-flight OPTIONS requests.
            if (req.method === 'OPTIONS') {
              res.statusCode = 204; // No Content
              return res.end();
            }

            // Pass control to the next middleware.
            next();
          });
        },
      },
    ].filter(Boolean), // Filter out any falsy values from the plugins array.
    // Configuration for resolving module imports.
    resolve: {
      // Define aliases for paths.
      alias: {
        // The '@' alias points to the 'client/src' directory.
        '@': path.resolve(__dirname, './client/src'),
      },
    },
    // The root directory of the client-side application.
    root: path.join(process.cwd(), 'client'),
    // Build-specific configuration.
    build: {
      // The output directory for the production build.
      outDir: path.join(process.cwd(), 'dist/public'),
      // Empty the output directory before building.
      emptyOutDir: true,
    },
    // Prevent Vite from clearing the screen on server start/restart.
    clearScreen: false,
    // Development server configuration.
    server: {
      // Hot Module Replacement (HMR) configuration.
      hmr: {
        // Disable the HMR overlay.
        overlay: false,
      },
      // Make the server accessible from the network.
      host: true,
      // The port for the development server.
      port: vitePort,
      // Allow all hosts to connect.
      allowedHosts: true,
      // Enable CORS for the dev server.
      cors: true,
      // Proxy for API requests.
      proxy: {
        // Requests to '/api/' will be forwarded to the backend server.
        '/api/': {
          target: 'http://localhost:3001',
          changeOrigin: true,
        },
      },
    },
    // CSS-specific configuration.
    css: {
      // Enable source maps for CSS in development.
      devSourcemap: true,
    },
    // esbuild-specific configuration.
    esbuild: {
      // Ensure source maps are generated by esbuild.
      sourcemap: true,
    },
  };
});
